name: Python Code Check

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  lint-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest Python 3.x version; adjust if needed (e.g., '3.9')

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest  # Install linting and testing tools
          # If your project has a requirements.txt, uncomment the next line
          # pip install -r requirements.txt

      # Step 4: Run linting with flake8
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --max-line-length=88 --extend-ignore=E203 --show-source --statistics

      # Step 5: Run tests with pytest (if you have test files)
      - name: Test with pytest
        run: |
          pytest  # Add --verbose or specific test paths if needed (e.g., pytest tests/)
